### ISSUE TITLE
Java home on OSX

### ISSUE THREAD

**Issue by bjkeller** [mernst/plume-lib#10]
Makefile does not work on Mac b/c of of missing JAVA_HOME.
According to following, convention on OS X since 10.5 is to use command /usr/libexec/java_home that returns home directory: https://developer.apple.com/library/mac/qa/qa1170/_index.html

[patch.txt](https://github.com/mernst/plume-lib/files/122068/patch.txt)

**Comment by mernst** [comment]
Fixed (in a slightly different way) by commit 03b3e05
