### ISSUE TITLE
Checker Framework annotation warnings when compiling against release version of plume.jar

### ISSUE THREAD

**Issue by bjkeller** [mernst/plume-lib#11]
When including plume.jar from the release, there were are warnings due to Checker Framework annotations:
1. classfile version warnings, which can be suppressed by -Xlint:-classfile 
2. missing symbol warnings, which can be suppressed by including checker-qual.jar in the classpath. I'm told that type annotations in plume are in the comments, and so the release version could be built without needing the checker framework jar.

**Comment by mernst** [comment]
What is "release version of plume.jar"?  Have you tried the latest release?

**Comment by bjkeller** [comment]
1.0.8. Sorry, didn't see you'd done another release.

The 1.0.9 plume.jar resolves the missing symbol warnings. Thanks!

Based on the checker framework documentation, I'm assuming the -Xlint:-classfile is necessary regardless if you don't want to see the warnings.

**Comment by mernst** [comment]
That's right.  I think the warning is only issued by a Java 8 compiler, but I'm not 100% sure.  It's innocuous.
