### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by stephanmg** [mernst/plume-lib#12]
Dear Mernst,

I'm not sure for me does this not work.
I receive access denied for the curl request.

Have you a suggestion?

**Comment by mernst** [comment]
I'm sorry you are having trouble.  I'd like to help, but your report leaves me unclear what you did.

What is the exact curl request you issued?
What is the exact output of that curl request?

**Comment by stephanmg** [comment]
Okay, the auth token was not correct, sorry...

I've a suggestion for your curl statement,
you cannot use / but you can specify --data-urlencode.


Best

**Comment by mernst** [comment]
You didn't specify, but I think you are talking about one of the curl commands in bin/trigger-travis.sh.  Is that right?  Which one?  Can you be concrete about your suggestion?  What is the exact change tat you propose?

**Comment by stephanmg** [comment]
You have a comment right before the curl command, that you cannot write a literal slash, e. g. "/".
You could try  "--data-urlencode" option for curl, this could help you! ;) 
Best,
Stephan

**Comment by mernst** [comment]
OK, thanks.  And, I'm glad things are now working for you!
