### ISSUE TITLE
JavaDoc errors in ArraysMDE

### ISSUE THREAD

**Issue by jsantino** [mernst/plume-lib#17]
In plume-lib/java/src/plume/ArraysMDE.java there is a subarray testing section starting ~ line 1167
the methods (isSubarray and isSubarrayEq) have:
   * @return the first index at which the second array starts in the first array,
   *    or -1 if the element is not found in the array

in the javadoc but they return booleans

**Comment by mernst** [comment]
You are right.  They were cut-and-pasted from indexOf, and not corrected.
I have fixed them in commit f2a433a.
Thanks for the report!
