### ISSUE TITLE
Feature Request: configurable travis-ci.com

### ISSUE THREAD

**Issue by hutchic** [mernst/plume-lib#19]
Having the ability to override `trigger-travis.sh` to use travis-ci.com could be beneficial

**Comment by mernst** [comment]
I agree.  I have added an optional `--pro` command-line argument to `trigger-travis.sh`, in commit cfb166d.

This is untested because I don't have any projects on travis-ci.com.  Could you please test my change?

**Comment by hutchic** [comment]
running out the door but I can PR this on Monday if you like:
```
TRAVIS_URL=travis-ci.org
if [ "$1" = "--pro" ] 
then
  TRAVIS_URL=travis-ci.com
  shift
fi
```

**Comment by mernst** [comment]
Right, I needed to quote the arguments to eq.  Thank you for catching that.  Commit 69d7bed adds the quoting.  Feel free to PR any further issues that you notice.

Thanks.

**Comment by hutchic** [comment]
LGTM
