### ISSUE TITLE
Question for trigger travis script

### ISSUE THREAD

**Issue by stephanmg** [mernst/plume-lib#20]
Dear @mernst,

I'm using your trigger travis script.
However, I cannot get it to work if I have to trigger a build from another organization,
i.e. I want to trigger a build of a repository from another organization.

Do you have an idea how to adapt?

**Comment by stephanmg** [comment]
Sorry.

**Comment by mernst** [comment]
The trigger-travis script takes as one of its arguments the GITHUBID.  From the documentation:

```
# Usage:
#   trigger-travis.sh [--pro] [--branch BRANCH] GITHUBID GITHUBPROJECT TRAVIS_ACCESS_TOKEN [MESSAGE]
# For example:
#   trigger-travis.sh typetools checker-framework `cat ~/private/.travis-access-token` "Trigger for testing"
```

You just need to have permission to run jobs in the repository you choose.

**Comment by stephanmg** [comment]
Thanks I realized that my ACCESS_TOKEN was wrong.
@mernst, however i fail to trigger a specific branch, is this supported by the script?

**Comment by mernst** [comment]
Did you see the optional argument `--branch BRANCH` in the documentation and in my comment above?

**Comment by stephanmg** [comment]
Thanks, I saw this.
But somehow it then triggers still the master branch instead of my branch foo.

**Comment by mernst** [comment]
I'm glad it is working for you now.  Happy hacking!
