### ISSUE TITLE
Using SimpleLog with @Option

### ISSUE THREAD

**Issue by bjkeller** [mernst/plume-lib#31]
The `plume.SimpleLog` class provides a nice way to perform logging, with the ability to log to both a file or to standard out. However, a `SimpleLog` cannot be used with `@Option`. Ideally, this would be possible with the ability for the user to indicate whether to use a file or standard out.

**Comment by mernst** [comment]
I have added a single-argument String constructor for SimpleLog, so this should work now.  It handles "-" as standard output.
